#!/usr/bin/env bash
set -e
. "$CLI_WORKDIR/cli/common"


cli_log "Start Airflow local containers"

docker compose up airflow-init

docker compose up

docker compose stop airflow-init

cli_log "Postgre and Redis containers stopped"